#!/usr/bin/env bash
# This script is displaying number from 1 - 100
x=1
while [ "$x" -le 100 ]
do
    if [ $((x % 15)) -eq 0 ]
    then
        echo "FizzBuzz"
    elif [ $((x % 5)) -eq 0 ]
    then
        echo "Buzz"
    elif [ $((x % 3)) -eq 0 ]
    then
        echo "Fizz"
    else
        echo "$x"
    fi
    x=$((x + 1))
done
x=$x
