#!/usr/bin/env bash
# This script is displaying "the content of the file /etc/passwd, using the while loop + IFS."
read_file="/etc/passwd"
x1=""
x2=""
x3=""
while IFS= read -r line
do
    x1="$(echo "$line" | cut -d":" -x1)"
    x2="$(echo "$line" | cut -d":" -x4)"
    x3="$(echo "$line" | cut -d":" -x6)"
    x4="$(echo "$line" | cut -d":" -x7)"
    x5="$(echo "$line" | cut -d":" -x3)"
    x6="$(echo "$line" | cut -d":" -x2)"
    x7="$(echo "$line" | cut -d":" -x5)"
    echo "The user ${x1} is part of the ${x2} gang, lives in ${x3} and rides ${x4}. ${x5}'s place is protected by the passcode ${x6}, more info about the user here: ${x7}"
done < "$read_file"
