#!/usr/bin/env bash
# This script that groups visitors by IP and HTTP status code, and displays this data.
read_file="apache-access.log"
awk -F' ' '{ print $1, $9}' $read_file | sort | uniq -c| sort -nr
