#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
x=10
while [ "$x" -gt 0 ]
do
    echo "Best School"
    if [ "$x" -eq 2 ]
    then
        echo "Hi"
    fi
    x=$((x - 1))
done
i=$i
